revert pipe for tee to show error

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -104,6 +104,13 @@ jobs:
         pytest-coverage-path: ./pytest-coverage.txt
         junitxml-path: ./pytest.xml
 
+    - name: Check test output
+      run: |
+        if [ ${{ steps.coverageComment.outputs.errors }} -gt '0' ] || [ ${{ steps.coverageComment.outputs.failures }} -ge '0']; then
+          echo "Errors found in pytest"
+          exit 1
+        fi
+
     - name: Update Coverage Badge
       if: github.event_name == 'push'
       uses: schneegans/dynamic-badges-action@v1.4.0
