fix multiline comment

diff --git a/.github/workflows/dependencies.yml b/.github/workflows/dependencies.yml
--- a/.github/workflows/dependencies.yml
+++ b/.github/workflows/dependencies.yml
@@ -61,7 +61,14 @@ jobs:
 
       - name: Diff dependencies
         run: |
-          echo "DIFF=$(diff -u branch.PKG-INFO main.PKG-INFO)" >> $GITHUB_ENV
+          # Write diff to env
+          echo "DIFF<<EOF" >> $GITHUB_ENV
+          set +e
+          diff -u branch.PKG-INFO main.PKG-INFO >> $GITHUB_ENV
+          set -e
+          echo "EOF" >> $GITHUB_ENV
+
+          # Test if it actually fails
           diff -u branch.PKG-INFO main.PKG-INFO
 
       - uses: mshick/add-pr-comment@v2
