Add back exit code handling
Since we are running with +e to have a chance to gran the logs after
a failure we need to make sure we preserve the exit code and exit
properly on falure.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -221,7 +221,13 @@ jobs:
           make test-setup
           set +e
           make test-integration-spark
+          # capture the exit code from the test run before stashing logs
+          EXIT_CODE=$?
           docker logs spark-thrift 2>&1 | tee spark-thrift.log
+          # bail out now if the test run was a failure
+          if [ $EXIT_CODE -ne 0 ]; then
+            exit $EXIT_CODE
+          fi
           make test-teardown
           mv .coverage .coverage.2
       - name: Upload spark-thrift log file
