Re-direct spark docker logs to a file (#867)
* Re-direct spark docker logs to a file

And use the upload-artifact action to save the log file on each
workflow run. I set the retention to 5 days since these logs can
get large and should really on be valuable when investigating
failures.

* Add back exit code handling

Since we are running with +e to have a chance to gran the logs after
a failure we need to make sure we preserve the exit code and exit
properly on falure.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -221,14 +221,21 @@ jobs:
           make test-setup
           set +e
           make test-integration-spark
+          # capture the exit code from the test run before stashing logs
           EXIT_CODE=$?
+          docker logs spark-thrift 2>&1 | tee spark-thrift.log
+          # bail out now if the test run was a failure
           if [ $EXIT_CODE -ne 0 ]; then
-              echo "Spark Thrift Server logs:"
-              docker logs spark-thrift --tail 50000
-              exit $EXIT_CODE
+            exit $EXIT_CODE
           fi
           make test-teardown
           mv .coverage .coverage.2
+      - name: Upload spark-thrift log file
+        uses: actions/upload-artifact@v3
+        with:
+          name: spark-thrift-logs
+          path: spark-thrift.log
+          retention-days: 5
       - name: Upload test results
         uses: actions/upload-artifact@v3
         with:
